dist: trusty

language: java

jdk:
- openjdk8

script: 

addons:
  sonarcloud:
    organization: "mogikanen9-github"

script:
  - mvn -f service/pom.xml test -B sonar:sonar -Dsonar.projectKey=rss2twitter -Dsonar.login=${SONAR_TOKEN}